### PR TITLE
effects added upto 111

### PR DESCRIPTION
**Pull request by ghost**
111 effects upto effect "chunchun" as listed in wled 10.0 code

### CODE REVIEW

**Comment by ghost** [comment]
Also added missing effects from 92-95

**Review by Skinah — APPROVED** [review]

**Comment by Skinah** [comment]
Its reporting that you have not signed off on the work?

**Comment by ghost** [comment]
> Its reporting that you have not signed off on the work?

Sorry, no idea how to do that.

**Comment by Skinah** [comment]
Sorry I approved another PR with simailar changes in it already that was a few weeks old and it has now stopped this one from being easy for me to include.. Changes are going in I just don't know Git well enough to fix this with the command line. Thanks for the changes and I'll include this in the next build.

**Comment by ghost** [comment]
@Skinah  I just had a look at that PR .
That does not add effects 92-95 as well as effect 111.
So maybe another PR is needed to include those too. Let me do that for you

**Pull request closed without merging**
