### PR TITLE
Add Save Preset 

### PR DESCRIPTION
**Pull request by ghost**
Hi Matt.
Added Save Preset Settings. Please have a look.
Thanks

### CODE REVIEW

**Review by Skinah — APPROVED** [review]

**Comment by Skinah** [comment]
I have merged them and will be doing some testing and any needed fix ups when I test. Thanks heaps for contributing, it looks like it has been done correctly and should work. Look forward to trying it out.

**Comment by ghost** [comment]
Sure. Would it be okay to add segment control to the binding? Should I go forward trying that?

**Comment by Skinah** [comment]
Yes segment and also support for RGBW (note the W for white channel) are missing. However I suspect it is better to write for the http api and forget about MQTT? I do prefer mqtt but it may be more prone to bugs in the wled project due to no one bothering to post issues and most users working with another platform.

**Comment by Skinah** [comment]
I would prefer a very quick over view of how a feature will work before doing the coding in case I disagree or have a different idea, then we can discuss it and work out which way is better before proceeding... But often it is easiest to have a play with the code to see what is possible so I understand doing the coding first :) Have fun and I hope you can build and test the changes before doing a PR?

**Comment by ghost** [comment]
I am afraid I can not test any changes as I dnt know how to compile bindings and have little to no experience with java. I just looked at your code online and edited foe save preset. 
So I think I'll have to wait until you add other functionalities yourself.

**Comment by Skinah** [comment]
Quick note, I changed the channels name to savePreset since it only saves 1 and not multiples. Testing it all out at the moment and having issues with WLED not having the new FX, must need to flash it again with USB and not use OTA method.

**Comment by ghost** [comment]
Oh ! I used OTA from 9.1 to 10.0. Worked fine for me though

**Pull request merged**
